# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template for migration file names, e.g. "%%(rev)s_%%(slug)s.py"
file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by running `pip install python-dateutil`.
# Any required timezone name can be used, such as `utc` or `gmt`.
# If left blank, the system's default timezone will be used.
# timezone =

# sys.path path, will be prepended to sys.path if present.
# values here are strings separated by whitespace.
# prepend_sys_path = .

# The target database URL.
sqlalchemy.url = sqlite:///./data/indexer.db

# ... other alembic config
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
